// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4hXtS46CG0238plZAgHlwwjGZSyTCaw4',
    appId: '1:798012052122:web:fdd6e4fc5b2a631ab04523',
    messagingSenderId: '798012052122',
    projectId: 'reddit-clone-c7c73',
    authDomain: 'reddit-clone-c7c73.firebaseapp.com',
    storageBucket: 'reddit-clone-c7c73.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSxdCAMvI6JF9tVaTQLDVamR9A115WGGM',
    appId: '1:798012052122:android:55893aea2ba202e4b04523',
    messagingSenderId: '798012052122',
    projectId: 'reddit-clone-c7c73',
    storageBucket: 'reddit-clone-c7c73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDowonUq0G4MVl_9X-JvWyStJ1K64ALhHI',
    appId: '1:798012052122:ios:4ba93c9204f538f6b04523',
    messagingSenderId: '798012052122',
    projectId: 'reddit-clone-c7c73',
    storageBucket: 'reddit-clone-c7c73.firebasestorage.app',
    iosClientId: '798012052122-vvcbeusbqciq3revgkl0i3ua7n43etdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDowonUq0G4MVl_9X-JvWyStJ1K64ALhHI',
    appId: '1:798012052122:ios:4ba93c9204f538f6b04523',
    messagingSenderId: '798012052122',
    projectId: 'reddit-clone-c7c73',
    storageBucket: 'reddit-clone-c7c73.firebasestorage.app',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4hXtS46CG0238plZAgHlwwjGZSyTCaw4',
    appId: '1:798012052122:web:4faf254146b77c4db04523',
    messagingSenderId: '798012052122',
    projectId: 'reddit-clone-c7c73',
    authDomain: 'reddit-clone-c7c73.firebaseapp.com',
    storageBucket: 'reddit-clone-c7c73.firebasestorage.app',
  );

}